services:
    db:
        image: mysql:latest
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8095:80
        environment:
            PMA_HOST: db

    web:
        build: Docker
        restart: on-failure
        volumes:
            - ./app:/app:rw
        ports:
            - 8010:80

volumes:
    db-data: null
